version: "3"
services:
  db:
    build:
      context: .
      dockerfile: $PWD/docker/Dockerfile.db
    restart: always
    hostname: postgres
    user: root
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "devdb"
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpasswd
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      TS: "Asia/Tokyo"
    volumes:
      - $PWD/.docker-compose-data/db/data:/var/lib/postgresql/data
      - $PWD/postgres/init:/docker-entrypoint-initdb.d
  grpc:
    build:
      context: .
      dockerfile: $PWD/docker/Dockerfile.grpc
    depends_on:
      - "db"
    links:
      - "db"
    environment:
      POSTGRES_DB: "devdb"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpasswd
    volumes:
      - .:/grpc
    ports:
      - 50051:50051
    expose:
      - "50051"
    tty: true
  gw:
    build:
      context: .
      dockerfile: $PWD/docker/Dockerfile.gw
    volumes:
      - .:/gateway
    links:
      - "grpc"
    ports:
      - 8081:8081
    tty: true
