jobs:
  build:
    executor:
      name: go/default
      tag: '1.17'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
orbs:
  go: circleci/go@1.7.0
  shellcheck: circleci/shellcheck@2.0.0
version: 2.1
workflows:
  main:
    jobs:
      - build
      - shellcheck/check:
          dir: ./
          