FROM golang:1.14-alpine

RUN apk add --no-cache git \
&& go get github.com/pilu/fresh

# コンテナログイン時のディレクトリ指定
WORKDIR /grpc
# ホストのファイルをコンテナの作業ディレクトリに移
ADD . /grpc

COPY go.mod .
COPY go.sum .
RUN go mod download && go mod tidy

COPY grpc/startup.sh /startup.sh
RUN chmod 744 /startup.sh

CMD [ "/startup.sh" ]