FROM golang:latest

# コンテナ内に作業ディレクトリを作成
# RUN mkdir /go/src/work
# コンテナログイン時のディレクトリ指定
#WORKDIR /go/src/work
# ホストのファイルをコンテナの作業ディレクトリに移行
#ADD . /go/src/work

WORKDIR /grpc
ADD . /grpc
COPY go.mod .
COPY go.sum .
RUN go mod download

CMD ["go", "run", "grpc/server.go"]