- uses: Platane/snk@master
  with:
    # github user name to read the contribution graph from (**required**)
    github_user_name: nakashimanh

    # path of the generated gif file
    # If left empty, the gif file will not be generated
    gif_out_path: dist/github-snake.gif

    # path of the generated svg file
    # If left empty, the svg file will not be generated
    svg_out_path: dist/github-snake.svg
